# Reemplazá estos valores con los que SonarQube te genera al crear el proyecto
sonar.projectKey=TU_USUARIO_TU_PROYECTO
sonar.organization=TU_ORGANIZACION

# Información del proyecto
sonar.projectName=todo-api
sonar.projectVersion=1.0

# Rutas del código fuente y tests
sonar.sources=app
sonar.tests=tests
sonar.language=py

# Exclusiones
sonar.exclusions=**/__pycache__/**,**/*.pyc

# Cobertura (opcional, requiere pytest-cov)
# sonar.python.coverage.reportPaths=coverage.xml
